export const BASE_URL = '/api/v1';
export const SIGNIN_ROUTE = BASE_URL + '/auth/signin';
export const SIGNUP_ROUTE = BASE_URL + '/auth/signup';
export const USER_BY_ID_ROUTE = BASE_URL + '/users/:id';
export const USER_ROUTE = BASE_URL + '/users';
export const USER_PER_PAGE_ROUTE = BASE_URL + 'users/p';
export const TRANSACTIONS_ROUTE = BASE_URL + '/transactions';
export const TRANSACTIONS_PER_PAGE_ROUTE = BASE_URL + '/transactions/p';
export const TRANSACTIONS_BY_ID_ROUTE = BASE_URL + '/transactions/:id';
